services/web/project/models.py
from . import db
from datetime import datetime, timedelta


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    platform_id = db.Column(db.String(120), unique=True, nullable=False)
    firstname = db.Column(db.String(120), nullable=False)
    lastname = db.Column(db.String(120), nullable=False)
    email = db.Column(db.String(120), nullable=False)
    pic = db.Column(db.String(120), nullable=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    type = db.Column(db.String(50))  # For inheritance

    deepdive_results = db.relationship('DeepdiveResult', backref='user', lazy=True, cascade="all, delete-orphan")

    __mapper_args__ = {
        'polymorphic_identity': 'user',
        'polymorphic_on': type
    }


class DeepdiveResult(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Text, db.ForeignKey('user.id'))
    # store links
    twitter_links = db.Column(db.Text)
    linkedin_links = db.Column(db.Text)
    reddit_links = db.Column(db.Text)
    facebook_links = db.Column(db.Text)
    instagram_links = db.Column(db.Text)
    tiktok_links = db.Column(db.Text)
    other_links = db.Column(db.Text)
    # sherlocked accounts
    possible_accounts = db.Column(db.Text)


class GoogleUser(User):
    id = db.Column(db.Integer, db.ForeignKey('user.id'), primary_key=True)

    __mapper_args__ = {
        'polymorphic_identity': 'google',
    }


class LinkedinUser(User):
    id = db.Column(db.Integer, db.ForeignKey('user.id'), primary_key=True)
    headline = db.Column(db.String(120), nullable=True)

    __mapper_args__ = {
        'polymorphic_identity': 'linkedin',
    }


class FacebookUser(User):
    id = db.Column(db.Integer, db.ForeignKey('user.id'), primary_key=True)

    __mapper_args__ = {
        'polymorphic_identity': 'facebook',
    }


def delete_old_entries():
    cutoff_time = datetime.utcnow() - timedelta(hours=24)
    old_user = User.query.filter(User.created_at < cutoff_time).all()

    for user in old_user:
        db.session.delete(user)

    db.session.commit()

services/web/project/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from os import urandom
from .extensions import oauth
from flask_apscheduler import APScheduler
from .utils import celery_init_app

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)

    oauth.init_app(app)

    app.config['SECRET_KEY'] = urandom(24)
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:////usr/src/app/instance/{DB_NAME}'
    app.config['CELERY'] = {"broker_url": "amqp://guest:guest@rabbitmq:5672//", "result_backend": "rpc://"}
    db.init_app(app)

    celery = celery_init_app(app)
    celery.set_default()

    from .routes import views
    app.register_blueprint(views)

    from .models import User, GoogleUser, LinkedinUser, FacebookUser, delete_old_entries, DeepdiveResult

    create_db(app)

    scheduler = APScheduler()
    scheduler.init_app(app)

    # Schedule the task to run once a day
    @scheduler.task('interval', id='delete_old_entries', hours=24)
    def scheduled_delete_old_entries():
        with app.app_context():
            delete_old_entries()

    scheduler.start()

    return app, celery


# created database
def create_db(app):
    if not path.exists('/usr/src/app/instance/' + DB_NAME):
        with app.app_context():
            db.create_all()
        print('Database created successfully.')

app, celery = create_app()
app.app_context().push()

services/web/project/routes.py
from flask import Blueprint, request, redirect, session, render_template, url_for, jsonify
import os
from dotenv import load_dotenv
from .extensions import oauth
from .osint import *
import ipinfo
import requests

load_dotenv('~/.env')  # load environment variables
views = Blueprint('views', __name__)


@views.route('/')
def index():
    return render_template('index.html')


@views.route('/login_successful')
def login_successful():
    user_info = session.get('user_info')
    service = session.get('service')

    if user_info and service:
        user_id = user_info['id']
        existing_data = DeepdiveResult.query.filter_by(user_id=user_id).first()

        if existing_data is None:
            get_deepdive.delay(user_id)

        user_ip = get_user_ip()
        location_info = None

        if user_ip is not None:
            user_info['user_ip'] = user_ip

            access_token = os.getenv('IPINFO')
            handler = ipinfo.getHandler(access_token)
            details = handler.getDetails(user_ip)

            location_info = {
                'city': details.city,
                'country': details.country_name,
                'coordinates': details.loc
            }

        user_info['ip_details'] = location_info
        session['user_info'] = user_info

        user = User.query.filter_by(platform_id=user_id).first()
        search_query = user.firstname + " " + user.lastname
        query = f'q=#gsc.tab=1&gsc.sort=&gsc.q={search_query}&gsc.tab=1&gsc.page=1'
        return redirect(url_for('views.user_login', _anchor=query))

    return redirect(url_for('views.index'))


@views.route('/user_login')
def user_login():
    service = session.get('service')
    user_info = session.get('user_info')
    print("SERVICE: " + service)
    if service == 'facebook':
        return render_template('facebook_index.html', user_info=user_info)
    return render_template(f'{service}_index.html', user_info=user_info)


def get_user_ip():
    if request.headers.getlist("X-Forwarded-For"):
        user_ip = request.headers.getlist("X-Forwarded-For")[0]
    else:
        user_ip = request.remote_addr
    return user_ip


@views.route('/get_all_links')
def get_all_links():
    user_info = session.get('user_info')
    user_id = user_info['id']

    deepdive_result = DeepdiveResult.query.filter_by(user_id=user_id).first()

    if deepdive_result:
        all_links = {
            'instagram': json.loads(deepdive_result.instagram_links) if deepdive_result.instagram_links else [],
            'reddit': json.loads(deepdive_result.reddit_links) if deepdive_result.reddit_links else [],
            'twitter': json.loads(deepdive_result.twitter_links) if deepdive_result.twitter_links else [],
            'linkedin': json.loads(deepdive_result.linkedin_links) if deepdive_result.linkedin_links else [],
            'other_links': json.loads(deepdive_result.other_links) if deepdive_result.other_links else [],
            'possible_accounts': json.loads(deepdive_result.possible_accounts) if deepdive_result.other_links else [],
            'facebook': json.loads(deepdive_result.facebook_links) if deepdive_result.facebook_links else []
        }
        return jsonify(all_links)
    else:
        return jsonify({'message': 'Data not ready'})


@views.route('/awareness')
def awareness():
    return render_template('awareness.html')


@views.route('/privacy')
def privacy():
    return render_template('privacy.html')


@views.route('/linkedin/login')
def linkedin_login():
    # Redirect the user to LinkedIn's authorization page
    print(os.getenv('REDIRECT_URI'))
    url = 'https://www.linkedin.com/oauth/v2/authorization'
    params = {
        'response_type': 'code',
        'client_id': os.getenv('LINKEDIN_CLIENT_ID'),
        'redirect_uri': os.getenv('REDIRECT_URI'),
        'state': 'foobar',
        'scope': 'r_basicprofile r_emailaddress',
    }
    # GET request for the URL with the concetinated params
    return redirect(requests.Request('GET', url, params=params).prepare().url)


@views.route('/linkedin/callback')
def linkedin_callback():
    # LinkedIn has redirected the user here with a code
    code = request.args.get('code')

    # Exchange this code for an access token
    url = 'https://www.linkedin.com/oauth/v2/accessToken'
    data = {
        'grant_type': 'authorization_code',
        'code': code,
        'client_id': os.getenv('LINKEDIN_CLIENT_ID'),
        'client_secret': os.getenv('LINKEDIN_CLIENT_SECRET'),
        'redirect_uri': os.getenv('REDIRECT_URI'),
    }
    response = requests.post(url, data=data)
    response.raise_for_status()  # Ensure we got a successful response

    # We have an access token
    access_token = response.json()['access_token']

    # Store the access token in the user's session
    session['access_token'] = access_token

    headers = {'Authorization': 'Bearer ' + access_token}
    user_info = {}
    response = requests.get('https://api.linkedin.com/v2/me', headers=headers)
    if response.status_code == 200:
        # Access token is valid
        user_info = response.json()
        # Process the user's LinkedIn profile data as needed
        print("LinkedIn Profile Data:", user_info)
    else:
        # Access token is invalid or expired
        print("Invalid Access Token")

    response = requests.get(
        'https://api.linkedin.com/v2/emailAddress?q=members&projection=(elements*(handle~))',
        headers=headers
    )

    if response.status_code == 200:
        # Successful email request
        email_data = response.json()
        print("LinkedIn Email Data:", email_data)

        # Extract the user's email address and add it to user_info
        if email_data.get('elements'):
            email_handle = email_data['elements'][0]['handle~']
            user_info['emailAddress'] = email_handle.get('emailAddress')
    else:
        # Email request failed
        print("Failed to fetch email")

    session['user_info'] = user_info
    session['service'] = 'linkedin'
    user = User.query.filter_by(platform_id=user_info['id'], type='linkedin').first()
    if not user:
        user = LinkedinUser(firstname=user_info['localizedFirstName'], lastname=user_info['localizedLastName'],
                            email=user_info['emailAddress'], platform_id=user_info['id'],
                            headline=user_info['localizedHeadline'])
        db.session.add(user)
        db.session.commit()

    return redirect(url_for('views.login_successful'))


@views.route('/google/')
def google():
    GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
    GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_KEY')
    CONF_URL = 'https://accounts.google.com/.well-known/openid-configuration'
    oauth.register(
        name='google',
        client_id=GOOGLE_CLIENT_ID,
        client_secret=GOOGLE_CLIENT_SECRET,
        server_metadata_url=CONF_URL,
        client_kwargs={
            'scope': 'openid email profile'  # add scopes ?
        }
    )

    # Redirect to google_auth function
    redirect_uri = url_for('views.google_auth', _external=True, _scheme='https')
    print(redirect_uri)
    return oauth.google.authorize_redirect(redirect_uri)


@views.route('/google/auth/')
def google_auth():
    token = oauth.google.authorize_access_token()
    response = oauth.google.get('https://www.googleapis.com/oauth2/v1/userinfo')
    user_info = response.json()
    print(" Google User ", user_info)
    session['user_info'] = user_info
    session['service'] = 'google'
    user = User.query.filter_by(platform_id=user_info['id'], type='google').first()
    if not user:
        user = GoogleUser(firstname=user_info['given_name'], lastname=user_info['family_name'],
                          email=user_info['email'], platform_id=user_info['id'])
        db.session.add(user)
        db.session.commit()

    print("Session after setting service:", session)
    return redirect(url_for('views.login_successful'))


@views.route('/process_facebook_data', methods=['POST'])
def process_facebook_data():
    user_info = request.json

    session['user_info'] = user_info
    session['service'] = 'facebook'
    print(user_info)

    user = User.query.filter_by(platform_id=user_info['id'], type='facebook').first()
    if not user:
        user = FacebookUser(firstname=user_info['first_name'], lastname=user_info['last_name'],
                            email=user_info['email'], platform_id=user_info['id'])
        db.session.add(user)
        db.session.commit()

    return jsonify({'status': 'success'})


@views.route('/imprint')
def imprint():
    return render_template('imprint.html')


@views.route('/logout')
def logout():
    user_info = session.get('user_info', None)
    if user_info:
        user_id = user_info.get('id')
        user = User.query.filter_by(platform_id=user_id).first()
        if user:
            DeepdiveResult.query.filter_by(user_id=user_id).delete()
            if isinstance(user, GoogleUser) or isinstance(user, LinkedinUser) or isinstance(user, FacebookUser):
                db.session.delete(user)

        db.session.commit()

    session.clear()
    return redirect(url_for('views.index'))  # Redirect to the home page

services/web/project/sherlock/sherlock/__init__.py
""" Sherlock Module

This module contains the main logic to search for usernames at social
networks.

"""

services/web/project/templates/awareness.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/site.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <title>Awareness</title>
</head>
<body>
{% extends "layout.html" %}
{% block content %}


<div class="awareness info-box border-0">

    <h2 style="color:black; font-family: 'Caveat', cursive; font-size: 4.5rem;">Wilkommen bei Datra!</h2>

    <!-- Account and IP Information Boxes -->
    <div class="info-container">
        <div class="card border-0 h-100">
            <div class="info-box border-0">
                <p style="margin-top: 20px;">
                    Hast du dich jemals gefragt, wie viel über dich im digitalen Raum auffindbar ist, basierend auf
                    deinen Social
                    Media Profilen?
                </p>
                <p>
                    Bei Datra nehmen wir diese Neugier ernst und bieten dir die Möglichkeit, einen Einblick zu erhalten.
                    Unsere
                    Plattform untersucht deine Daten und deckt auf, inwiefern diese Rückschlüsse auf andere Profile und
                    persönliche
                    Informationen zulassen.
                </p>

                <p>
                    Der Prozess ist einfach und sicher: Melde dich einfach mit dem Social Login an. Keine Bange, wir
                    legen großen
                    Wert auf deine Privatsphäre. Deine Daten werden sofort gelöscht, sobald du dich ausloggst. Und falls
                    du es
                    einmal vergisst, keine Sorge – wir entfernen alle deine Daten automatisch nach 24 Stunden <i class="fa-regular fa-face-grin-wink"></i>
                </p>
            </div>
        </div>

        <div class="card border-0 h-100">
            <div class="info-box border-0">
                <img src="{{ url_for('static', filename='images/drawkit-grape-pack-illustration-1.svg') }}"
                     alt="My Happy SVG" style="width: 400px; height: auto; align: center;"/>
            </div>
        </div>
    </div>


    <h2 style="margin-top: 50px; color: black;">Datensicherheit betrifft uns alle</h2>
    <p style="margin-top: 20px;">
        Datensicherheit ist ein wichtiges Thema in der heutigen digitalen Welt, da immer mehr persönliche Informationen
        online geteilt werden.
        Wir alle tragen eine gewisse Verantwortung dafür, wie wir unsere Daten schützen und sicherstellen, dass sie
        nicht in die falschen Hände geraten.
        <br>
        Wenn wir uns nicht um unsere Datensicherheit kümmern, können unsere persönlichen Informationen für unerwünschte
        Zwecke verwendet werden.
        <br>
        <br>
    <h4>Welche Gefahren gibt es?</h4>
    Zum Beispiel können unsere E-Mail-Adresse, unser Name und unser Geburtsdatum von Marketing-Unternehmen genutzt
    werden, um uns mit unerwünschten E-Mails und Werbung zu bombardieren. Wir können auch Opfer von Identitätsdiebstahl
    werden,
    wenn Kriminelle unsere Daten stehlen und für ihre eigenen Zwecke nutzen. Deshalb sollten wir uns bewusst sein, wie
    wir unsere Daten schützen können. Wir sollten starke Passwörter verwenden, regelmäßig unsere Software aktualisieren
    und sichere Verbindungen verwenden, wenn wir im Internet surfen.
    <br>
    <br>
    Wir sollten auch vorsichtig sein, welche persönlichen Informationen wir online teilen und nur vertrauenswürdige
    Cloud-Dienste nutzen, die eine sichere Verschlüsselung unserer Daten anbieten.
    Es ist auch wichtig, dass wir uns bewusst sind, dass Unternehmen auch eine Verantwortung für die Datensicherheit
    tragen. Unternehmen sollten sicherstellen, dass sie die erforderlichen Schritte unternehmen, um die Daten ihrer
    Kunden
    zu schützen und sicherzustellen, dass diese nicht in die falschen Hände geraten.
    <br>
    <br>
    Dienste wie die <a href="https://www.watchlist-internet.at/">Watchlist Internet</a> bieten unter anderem
    Informationen zu unseriösen Webseiten und weitere interessante Tipps zum Thema Sicherheit im Internet.
    Solltest du Opfer eines Betrugs geworden sein, melde dich sofort bei den entsprechenden Behörden.
    <br>
    <br>
    <h4>Wie kann ich mich konkret schützen?</h4>
    <ul>
        <li>Achte darauf, ob dein Profil öffentlich zugänglich ist. So können andere Benutzer:innen auf deine
            Profilinformationen zugreifen, einschließlich Fotos, Freunde, Posts und Kommentare
        </li>
        <li>Achte auch auf deine Posteinstellungen, sollten diese nämlich Öffentich sein, können auch Personen die nicht
            deine Kontakte sind sie sehen
        </li>
        <li>Teile keine sensiblen Informationen, sowie deine Heimadresse, Telefonnummer oder auch die Adresse deiner
            Schule
        </li>
        <li>Aktiviere die Zwei-Faktor-Authentifizierung, damit auch wirklich nur du Zugriff auf dein Konto hast</li>
        <li>Verwende ein sicheres Passwort, welches stark und einzigartig ist und verwende wenn möglich auch einen
            Password Manager
        </li>
        <li>Wenn möglich, deaktiviere die Standortverfolgung in den Einstellungen</li>
        <li>Überprüfe die App-Berechtigungen auf deinem Gerät, z.B. ob ein Service Zugriff auf dein Mikrofon, deine
            Kontakte oder weiteres hat
        </li>
        <li>Füge nur Leute in deine Kontaktliste hinzu die du auch wirklich kennst</li>
        <li>Melde verdächtige Aktivitäten! Sollte dir eine Situation unangenehm sein oder hast du den Verdacht dein
            Profil könnte gehackt worden sein, melde dies umgehend
        </li>
    </ul>


</div>

{% endblock %}
</body>
</html>

services/web/project/templates/imprint.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/site.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <title>Impressum</title>
</head>
<body>
{% extends "layout.html" %}
{% block content %}
<div class="imprint">

    <h2 style="margin-top: 50px;">Impressum</h2>
    <p style="margin-top: 20px;">
        <b>Medieninhaber, Herausgeber und Redaktion:</b><br><br>
      
        Forschungsgruppe Security & Privacy<br>
        Fakultät für Informatik<br>
        Universität Wien<br>
        Kolingasse 14-16, 5. OG<br>
        1090 Wien<br>
        Telefon: +43 1 4277 79702<br>
        sec@cs.univie.ac.at<br>
        
    </p>
</div>

{% endblock %}
</body>
</html>

services/web/project/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/site.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='fontawesome/css/all.min.css') }}"/>
    <style>
        iframe { 
            margin-top: 10px;
        }

    </style>
</head>
<body class="index-background">

{% extends "layout.html" %}
{% block content %}
<!-- Your HTML content here -->
<div class="left-container">
    <!-- Header-->
    <header class="py-5">
        <div class="container px-lg-5">
            <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
                <div class="m-4 m-lg-5">
                    <h1 class="display-5 fw-bold">Dein Tool für Datentransparenz und Datensicherheit</h1>
                    <div style="margin-top: 65px"></div>

                    <a class="btn btn-secondary" style="background-color: #0082ca; border-color: #0082ca;" height: 40px;
                       padding-top: 14px;" href="/linkedin/login" role="button"><i class="fab fa-linkedin me-2"></i>Anmelden
                    mit LinkedIn</a>

                    <a class="btn btn-secondary"
                       style="background-color: #dd4b39; border-color: #dd4b39; height: 40px; padding-top: 7px;"
                       href="google/" role="button"><i class="fab fa-google me-2"></i>Anmelden mit Google</a>
                    <script async defer crossorigin="anonymous"
                            src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v16.0&appId=184791784339843&autoLogAppEvents=1"
                            nonce="TkNf6DkU"></script>
                    <div class="fb-login-button" size="large"
                         data-scope="public_profile,email,user_age_range,user_gender,user_location,user_hometown,user_birthday,user_posts"
                         data-width="250" data-size="" data-button-type="" data-layout="" data-auto-logout-link="false"
                         data-use-continue-as="false" onlogin="checkLoginState();"></div>
                    <div id="status"></div>
                </div>
            </div>
    </header>
</div>
<script src="{{ url_for('static', filename='js/facebook.js') }}"></script>
<script src="{{ url_for('static', filename='js/linkedin.js') }}"></script>
<script src="https://accounts.google.com/gsi/client" async></script>

{% endblock %}

</body>
</html>

services/web/project/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ title }} - DaTra</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" />
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/site.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='fontawesome/css/all.min.css') }}" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm mb-3 fixed-top">
            <div class="container px-lg-5">
                <a class="navbar-brand" href="{{ url_for('views.index') }}">D A T R A</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('views.index') }}">Start</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('views.awareness') }}">Informationen</a>
                        </li>
                        <li>
                            <a class="nav-link" href="{{ url_for('views.login_successful') }}">Profil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('views.logout') }}">Ausloggen</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            {% block content %}{% endblock %}
        </main>
    </div>

    <footer class="footer bg-dark fixed-bottom">
        <div class="container"><p class="m-0 text-center text-dark">ein Projekt der Universität Wien, gefördert durch netidee&nbsp; &middot; &nbsp;<a href="{{ url_for('views.privacy') }}">Datenschutzerklärung</a>&nbsp; &middot; &nbsp;<a href="{{ url_for('views.imprint') }}">Impressum</a></p></div>
    </footer>

    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    {% block scripts %}{% endblock %}
</body>
</html>

services/web/project/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/site.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <title>Awareness</title>
</head>
<body>
{% extends "layout.html" %}
{% block content %}
<div class="awareness">

    <h2 style="margin-top: 50px;" align="center">Erfahre mehr über dich selbst</h2>
    <p style="margin-top: 20px;">
        Thank you! We will mail results when done.
    </p>
</div>



{% endblock %}
</body>
</html>